project_name: ncregistry
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: ncregistry
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
brews:
  - name: ncregistry
    tap:
      owner: stenstromen
      name: homebrew-tap
    commit_author:
      name: stenstromen
    folder: Formula
    homepage: https://github.com/Stenstromen/ncregistry
    description: The NcRegistry Go binary is a powerful command-line tool designed to streamline interaction with Docker registries